// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_-2eUMpjFH2eRM6V_YSJL0tEm9iMDpnw',
    appId: '1:759483775383:web:8c13d62f3f267276026cd2',
    messagingSenderId: '759483775383',
    projectId: 'farmer-app-871a9',
    authDomain: 'farmer-app-871a9.firebaseapp.com',
    storageBucket: 'farmer-app-871a9.firebasestorage.app',
    measurementId: 'G-KP4N4PKHEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBULS8nN6nu9wGXC31Jq2KsDi2sl34Iyac',
    appId: '1:759483775383:android:e97b9a40eb58b8ab026cd2',
    messagingSenderId: '759483775383',
    projectId: 'farmer-app-871a9',
    storageBucket: 'farmer-app-871a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRt0liADAxEn87sOD7fZECfPMRp1rNDPU',
    appId: '1:759483775383:ios:d68a9b661fc94194026cd2',
    messagingSenderId: '759483775383',
    projectId: 'farmer-app-871a9',
    storageBucket: 'farmer-app-871a9.firebasestorage.app',
    iosBundleId: 'com.example.farmerApp',
  );
}
